# name: library_management

include:
  - ./auth_service/compose.yaml

services:
  textbook_rental_service:
    # A lightweight echo server to act as a placeholder for your downstream service
    image: mendhak/http-https-echo:30
    container_name: textbook_rental_service
    networks:
      - backend_app_net

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend_app_net
    depends_on:
      - auth_service
      - textbook_rental_service

volumes:
  postgres_data:

networks:
  backend_app_net: