-- 02_tables.sql

-- Set search path to use our auth schema
SET search_path TO auth;

-- Role table
CREATE TABLE IF NOT EXISTS auth.role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) UNIQUE NOT NULL
);

-- Users table
CREATE TABLE IF NOT EXISTS auth.user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- User roles table
CREATE TABLE IF NOT EXISTS auth.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.user(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES auth.role(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role_id)
);
 
-- Login credentials table
CREATE TABLE IF NOT EXISTS auth.login_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.user(id) ON DELETE CASCADE,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_login_credential_username ON auth.login_credential(username) where is_active = true;
CREATE UNIQUE INDEX IF NOT EXISTS idx_login_credential_user_id ON auth.login_credential(user_id) where is_active = true;
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_roles_user_role ON auth.user_roles(user_id, role_id) where is_active = true;