-- 02_tables.sql

-- Set search path to use our auth schema
SET search_path TO auth;

-- Role table
CREATE TABLE IF NOT EXISTS auth.role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) UNIQUE NOT NULL
);

-- Users table
CREATE TABLE IF NOT EXISTS auth.user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- User roles table
CREATE TABLE IF NOT EXISTS auth.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.user(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES auth.role(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);
 
-- Login credentials table
CREATE TABLE IF NOT EXISTS auth.login_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.user(id) ON DELETE CASCADE,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    salt VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

--Refresh token table
-- TIMESTAMPTZ (Postgresql) and TIMESTAMP WITH TIME ZONE are the same
CREATE TABLE IF NOT EXISTS auth.refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.user(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) UNIQUE NOT NULL,
    --is_revoked BOOLEAN DEFAULT FALSE,
    --created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    --replaced_by_token VARCHAR(255) NULL -- For Reuse Detection

    -- Token lifecycle
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Revocation and Rotation tracking
    revoked_at TIMESTAMP WITH TIME ZONE, -- If NULL, the token is technically "active"
    
    -- Self-referencing foreign key to track the chain of token rotation
    replaced_by_token_id bigint REFERENCES auth.refresh_token(id) ON DELETE SET NULL
);

-- Indexes

-- Indexes for soft-delete aware unique constraints
-- Allow username reuse only when deleted
CREATE UNIQUE INDEX IF NOT EXISTS idx_login_credential_username_active 
    ON auth.login_credential(username) 
    WHERE deleted_at IS NULL;

-- Allow multiple credentials per user (only one active)
CREATE UNIQUE INDEX IF NOT EXISTS idx_login_credential_user_active 
    ON auth.login_credential(user_id) 
    WHERE deleted_at IS NULL;

-- Allow one active role per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_roles_user_role_active 
    ON auth.user_roles(user_id, role_id) 
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_refresh_token_token_hash
    ON refresh_token(token_hash);